name: Setup Go Environment
description: Setup the Go development environment with dependencies and tools
inputs:
  ref:
    description: The git ref to build on
    required: false
  fetch-depth:
    description: The depth of the git checkout
    required: false
  fetch-tags:
    description: Whether to fetch tags
    required: false
  go-version:
    description: The Go version to use
    required: false
    default: "1.24"
  install-deps:
    description: Whether to download Go dependencies
    required: false
    default: "true"
  install-tools:
    description: Whether to install additional tools (helm, kubectl, golangci-lint)
    required: false
    default: "false"
  build-binary:
    description: Whether to build the function binary
    required: false
    default: "false"
  submodules:
    description: Whether to fetch submodules
    required: false
    default: "false"

runs:
  using: composite
  steps:
  - name: Checkout Code
    uses: actions/checkout@v5
    with:
      ref: ${{ inputs.ref }}
      fetch-depth: ${{ inputs.fetch-depth }}
      fetch-tags: ${{ inputs.fetch-tags }}
      submodules: ${{ inputs.submodules }}

  - name: Set up Go
    uses: actions/setup-go@v5
    with:
      go-version: ${{ inputs.go-version }}
      cache: true

  - name: Download Go dependencies
    if: inputs.install-deps == 'true'
    shell: bash
    run: go mod download

  - name: Tidy Go module dependencies
    if: inputs.install-deps == 'true'
    shell: bash
    run: go mod tidy

  - name: Set up Helm
    if: inputs.install-tools == 'true'
    uses: azure/setup-helm@v4
    with:
      version: latest

  - name: Set up kubectl
    if: inputs.install-tools == 'true'
    uses: azure/setup-kubectl@v4
    with:
      version: latest

  - name: Build KRM Helm function binary
    if: inputs.build-binary == 'true'
    shell: bash
    run: go build -o bin/function ./cmd/function