name: Setup Go Environment
description: Setup the Go development environment with dependencies and tools
inputs:
  go-version:
    description: The Go version to use
    required: false
    default: "1.24"
  install-deps:
    description: Whether to download Go dependencies
    required: false
    default: "true"
  install-tools:
    description: Whether to install additional tools (helm, kubectl, golangci-lint)
    required: false
    default: "false"
  build-binary:
    description: Whether to build the function binary
    required: false
    default: "false"

runs:
  using: composite
  steps:
  - name: Set up Go
    uses: actions/setup-go@v5
    with:
      go-version: ${{ inputs.go-version }}
      cache: true

  - name: Download Go dependencies
    if: inputs.install-deps == 'true'
    shell: bash
    run: go mod download

  - name: Tidy Go module dependencies
    if: inputs.install-deps == 'true'
    shell: bash
    run: go mod tidy

  - name: Set up Helm
    if: inputs.install-tools == 'true'
    uses: azure/setup-helm@v4
    with:
      version: latest

  - name: Set up kubectl
    if: inputs.install-tools == 'true'
    uses: azure/setup-kubectl@v4
    with:
      version: latest

  - name: Build KRM Helm function binary
    if: inputs.build-binary == 'true'
    shell: bash
    run: go build -o bin/function ./cmd/function