apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: helm-rancher
generators:
- release.yaml
# Rancher's HelmChart resource can reference secrets for values, but not configmaps.
# Therefore, we use a secretGenerator here.
secretGenerator:
- name: my-app-values
  files:
  - values.yaml
  options:
    annotations:
      krm.kubed.io/helm-values: "my-app"
