name: PR Check

on:
  pull_request:
    branches:
    - main

jobs:
  pr-check:
    name: Test Quality
    runs-on: ubuntu-latest
    steps:
    - name: Setup Go Environment
      id: setup
      uses: ./.github/actions/setup
      with:
        go-version: '1.24'
        install-deps: 'true'
        build-binary: 'true'

    - name: Run Quality Assurance Checks
      id: qa
      uses: ./.github/actions/qa

    - name: Run all Go tests
      id: test
      run: go test -v ./...
